services:
  mongodb:
    image: mongo:7
    container_name: loongis-mongodb
    restart: unless-stopped

    ports:
      - "27017:27017"

    volumes:
      - loongis-mongo-data:/data/db

volumes:
  loongis-mongo-data: